# --------------------------------------------------
# 1. Configuración de Conexión a MySQL
# --------------------------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------------------------------------------------
# 2. Configuración de JPA/Hibernate para MySQL (Se mantienen fijas)
# --------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --------------------------------------------------
# 3. Configuración de HikariCP (Pool de Conexiones) (Se mantienen fijas)
# --------------------------------------------------
spring.datasource.hikari.cache-prep-stmts=true
spring.datasource.hikari.statement-cache-size=250

# --------------------------------------------------
# 4. Configuración de JWT (Referencia a variables de entorno)
# --------------------------------------------------
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#----------------------------------------------------
# 5. CONFIGURAVION PARA MAIL (Referencia a variables de entorno)
#----------------------------------------------------
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.default-encoding=${MAIL_DEFAULT_ENCODING}

# --------------------------------------------------
# 6. CONFIGURACIÓN DE GOOGLE OAUTH (Referencia a variables de entorno)
# --------------------------------------------------
google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID}

# Frontend URL
app.frontend.url=${APP_FRONTEND_URL}


# --------------------------------------------------
# 7. AWS S3 (Referencia a variables de entorno)
# --------------------------------------------------
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}

# Swagger UI accesible en /swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/v3/api-docs

# Para escanear solo tus controllers (tu paquete real)
springdoc.packagesToScan=com.tetris.tetrisburger_backend.infrastructure.rest.controller

# (Opcional) para incluir solo rutas /api/**
springdoc.pathsToMatch=/api/**
